spring.application.name=Hotel-Booking-System

# Đường dẫn thư mục upload ảnh (bên ngoài project, dùng cho runtime)
app.upload.rooms-dir=uploads/rooms

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=HotelManagemen_New;encrypt=true;trustServerCertificate=true;sendStringParametersAsUnicode=true;
spring.datasource.username=sa
spring.datasource.password=123

# Cấu hình Hibernate JPA tự động tạo bảng từ Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =============================================================
# VNPAY SANDBOX CONFIGURATION
# =============================================================
vnpay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.tmnCode=D6ELPNNF
vnpay.hashSecret=KPOPXEJ9RL0CSEL3IO6O0W24XO59PWPA
vnpay.returnUrl=http://localhost:8080/bookings/vnpay-callback