spring.application.name=Hotel-Booking-System

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=Hotel_Booking_System;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=123

# Cấu hình Hibernate JPA tự động tạo bảng từ Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true